# Naïve RAG configuration (baseline)
extends: base.yaml

# Simplified retrieval
retrieval:
  top_k: 5
  rerank_top_k: 5  # Same as top_k to disable reranking
  fusion_method: "dense_only"  # Only dense retrieval
  bm25_weight: 0.0
  dense_weight: 1.0

# Disable advanced features
prompt_fanning:
  enabled: false

guardrails:
  answerability_threshold: 0.0  # Disable answerability check
  self_check_enabled: false
  answerability_enabled: false  # Completely disable answerability guardrails
  max_citations: 8  # Increased from 5

# Simple chunking
chunking:
  chunk_size: 400
  chunk_overlap: 50

# Basic performance settings
performance:
  max_tokens: 2000
  temperature: 0.0
